INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Annette', 'Hinton', 'CARDIOLOGIST', 'Dunn-Koch', 'annette.hinton@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Elizabeth', 'Palmer', 'CARDIOLOGIST', 'Smith-Johnson', 'elizabeth.palmer@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Barbara', 'Smith', 'CARDIOLOGIST', 'Nichols-Hunt', 'barbara.smith@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Melissa', 'Smith', 'CARDIOLOGIST', 'Malone PLC', 'melissa.smith@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Bonnie', 'Lewis', 'CARDIOLOGIST', 'Peterson, Allen and Garrett', 'bonnie.lewis@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Chad', 'Marshall', 'DERMATOLOGIST', 'Rosario Inc', 'chad.marshall@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Christopher', 'Frank', 'DERMATOLOGIST', 'Tucker-Davis', 'christopher.frank@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Karen', 'Jones', 'DERMATOLOGIST', 'Miller, Wagner and Lopez', 'karen.jones@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Luis', 'Daniels', 'ENDOCRINOLOGIST', 'Solomon-Haynes', 'luis.daniels@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Bradley', 'Hall', 'ENDOCRINOLOGIST', 'Soto-Day', 'bradley.hall@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Jorge', 'Carter', 'ENDOCRINOLOGIST', 'Kelly, Brown and Evans', 'jorge.carter@example.com');
INSERT INTO doctor (nombre, apellido, especialidad, medical_center, email) VALUES ('Anita', 'Weaver', 'GASTROENTEROLOGIST', 'Henson-Chavez', 'anita.weaver@example.com');
INSERT INTO patient (nombre, apellido, identificacion, edad, telefono) VALUES ('Roger', 'Murphy', 77080, 98, '001-706-623-1035');
